audit_header: false
title: Richmond Real Estate Video Blog with Mark Adams
description: >-
  Our mission at Mark Adams & Associates is to be your best resource for
  Richmond real estate advice. Whether you are a buyer, seller, or investor, our
  team of professionals can answer any questions you might have about real
  estate. If you are looking to buy or sell a home, you can get all the
  information and the latest updates, tips, and tricks from The Mark Adams &
  Associates, your professional Richmond Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: Testimonials
    url: https://www.markadamsteam.com/testimonials/
client:
  name: Mark Adams
  title:
  license_number:
  about_markdown: >-
    We understand that buying or selling a home is more than just a transaction:
    it’s a life-changing experience and that’s what it is meant to be. We
    believe, both professionally and personally, that there is nothing better
    than owning a home. Making your home your own, with your favorite things and
    then making memories to last a lifetime, with family and friends, is what
    it’s all about. That’s why our team of highly-seasoned real estate
    professionals is dedicated to providing exceptional, personalized service
    for all of our clients. We take great pride in the relationships we build
    and always work relentlessly on the client’s behalf to help them achieve
    their real estate goals.
  brand: Mark Adams & Associates
  brokerage: eXp Realty
  market: Richmond
  address: 6802 Paragon Place, Richmond, VA 23230
  phone: 804-237-8585
  phone_type:
  phone2:
  phone2_type:
  email: office@markadamsteam.com
  url: http://markadamsblog.com
forms:
  sitekey: 6LcKHSsaAAAAAI1B5pfFwBPg65Q8n9GjNlAQhhMU
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.markadamsteam.com/home-worth
  second_CTA_text: Home Search
  second_CTA_URL: https://markadams.exprealty.com/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Richmond Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://www.markadamsteam.com/home-worth
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Richmond Home?
    CTA_text2: Search the entire MLS for your Richmond home.
    CTA_link_text2: Search the MLS
    CTA_url2: https://markadams.exprealty.com/
third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_link_text3: Client Testimonials
    CTA_url3: https://www.markadamsteam.com/testimonials/
lender:
  show_section: true
  header_text: Local Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name: Greg Cowart
  license_number: 'NMLS #: 204399'
  company: Branch Manager | Loan Originator
  company_license_number:
  phone: 804-306-6463
  email: gcowart@nfmlending.com
  url: http://gregcowart.com
  lender_cta: https://bp.nfmlending.com/apply/gcowart
  lender_cta_text: Apply Now
socials:
  review_sm_icons: false
  facebook_url: >-
    http://business.facebook.com/markadamsassociates/?business_id=10153283000255325
  linkedin_url: https://www.linkedin.com/in/markadamsteam/
  youtube_url: https://www.youtube.com/channel/UCZbv1oVEFX4aT5s4K-9-v6A
  twitter_url:
  instagram_url: https://www.instagram.com/markadamsandassociates/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Richmond Real Estate Podcast with Mark Adams
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Richmond
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Mark Adams & Associates - your
    professional Richmond Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Richmond, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Mark Adams
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /uploads/png-dog-lovers-final-300.png
  logo_width_number: 30
  hero_text: Richmond Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /uploads/untitled-design-2.png
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#85a14d'
  theme_color: '#125176'
  theme_text_color: '#125176'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#000000'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
